### ISSUE TITLE
Please, switch to the current branch by default

### ISSUE THREAD

**Issue by Anton-Latukha** [chris-martin/text-replace#2]
Noticed that the repository has `0.0.0.8` branch as default.

So looking at the sources or cloning also represents that branch.

---

Thanks for the project.

Happy to see the trie bulk replacements.

A good example I found is: escaping the special language characters.

**Comment by chris-martin** [comment]
I've cleaned up the repo and gone back to the normal thing of just having a single main branch, using tags for versions. Trying to keep switching the default branch was a pain.

Thank you for your comments :)
